function digimonSets() {
  const types = [
    {
      id: 706,
      name: "BT-01: Booster New Evolution",
      release_date_jp: "2020-05-15",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 1156,
      name: "BT-02: Booster Ultimate Power",
      release_date_jp: "2020-07-22",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 1158,
      name: "BT-03: Booster Union Impact",
      release_date_jp: "2020-10-30",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 1159,
      name: "BT-04: Booster Great Legend",
      release_date_jp: "2020-12-18",
      release_date_en: "2021-06-11",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 12469,
      name: "BT-04: Booster Great Legend/Gallery",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 3316,
      name: "BT-05: Booster Battle Of Omni",
      release_date_jp: "2021-02-26",
      release_date_en: "2021-08-06",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 3813,
      name: "BT-06: Booster Double Diamond",
      release_date_jp: "2021-05-28",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 6761,
      name: "BT-07: Booster Next Adventure",
      release_date_jp: "2021-08-27",
      release_date_en: "2022-03-04",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 12759,
      name: "BT-08: Booster New Awakening",
      release_date_jp: "2021-11-26",
      release_date_en: "2022-05-13",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 10098,
      name: "BT-09: Booster X Record",
      release_date_jp: "2022-02-25",
      release_date_en: "2022-07-29",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 11192,
      name: "BT-10: Booster Xros Encounter",
      release_date_jp: "2022-05-27",
      release_date_en: "2022-10-14",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 703,
      name: "BT01-03: Release Special Booster Ver.1.0",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 1145,
      name: "BT01-03: Release Special Booster Ver.1.5",
      release_date_jp: null,
      release_date_en: "2021-03-12",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 13054,
      name: "BTC-01: Booster Ultimate Evolution",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 6945,
      name: "Classic Collection EX-01",
      release_date_jp: "2021-07-30",
      release_date_en: "2021-12-10",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 9082,
      name: "Digital Hazard EX-02",
      release_date_jp: "2021-12-24",
      release_date_en: "2022-06-24",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 12749,
      name: "1-Year Anniversary Promo Pack",
      release_date_jp: "2021-05-28",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 5965,
      name: "1st Anniversary Adventure Pack",
      release_date_jp: "2021-06-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7133,
      name: "1st Anniversary Card Catalog",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 5627,
      name: "1st Anniversary Promotion Pack",
      release_date_jp: "2020-03-26",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12755,
      name: "1st Anniversary SR Bonus cards",
      release_date_jp: "2021-04-23",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13632,
      name: "2022 Regionals",
      release_date_jp: null,
      release_date_en: "2021-05-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11846,
      name: "2nd Anniversary Promotion Pack",
      release_date_jp: "2022-02-25",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12474,
      name: "Battle of Omni Pre-Release Pack",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11914,
      name: "Box Promotion Pack -Next Adventure-",
      release_date_jp: null,
      release_date_en: "2022-03-04",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11424,
      name: "Championship 2021 Finals",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11421,
      name: "Championship 2021 Finals Tamer's Evolution Pack",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 701,
      name: "Dash Pack Ver. 1.0",
      release_date_jp: null,
      release_date_en: "2021-01-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 1885,
      name: "Dash Pack Ver. 1.5",
      release_date_jp: null,
      release_date_en: "2021-03-12",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7189,
      name: "DC-1 Grand Prix",
      release_date_jp: "2021-07-17",
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12337,
      name: "Digimon Card Game Fest",
      release_date_jp: null,
      release_date_en: "2022-03-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 9775,
      name: "GB-01: Digimon Card Game Gift Box",
      release_date_jp: null,
      release_date_en: "2022-12-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 8790,
      name: "Double Diamond Dash Pack",
      release_date_jp: null,
      release_date_en: "2021-10-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12475,
      name: "Double Diamond Pre-Release Pack",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11099,
      name: "Event Pack",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11419,
      name: "Event Pack 2",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 6922,
      name: "Evolution Cup",
      release_date_jp: "1970-01-01",
      release_date_en: "2021-11-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 9774,
      name: "Ghost Game Promo Pack",
      release_date_jp: "2022-11-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 1884,
      name: "Great Dash Pack",
      release_date_jp: null,
      release_date_en: "2021-06-11",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 5857,
      name: "Great Legend Power Up Pack",
      release_date_jp: null,
      release_date_en: "2021-06-11",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12459,
      name: "Great Legend Pre-Release Pack",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12762,
      name: "Judge Pack",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13211,
      name: "June Premier TO Event",
      release_date_jp: null,
      release_date_en: "2021-06-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 10773,
      name: "Limited Card Set ONLINE",
      release_date_jp: "2021-12-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13062,
      name: "Luxury processing ver. Tamer Cards",
      release_date_jp: "2022-04-22",
      release_date_en: "2022-10-14",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7195,
      name: "Memorial Collection 01",
      release_date_jp: "2021-08-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7196,
      name: "Memorial Collection 02",
      release_date_jp: "2021-08-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7273,
      name: "Memorial Collection 03",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13074,
      name: "New Awakening Pre-Release Pack",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13077,
      name: "New Awakening Pre-Release Promotion",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12535,
      name: "Next Adventure Pre-Release Pack",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11760,
      name: "Next Adventure Pre-Release Promotion",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 3320,
      name: "Official Tournament Pack Vol. 1",
      release_date_jp: null,
      release_date_en: "2021-02-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13254,
      name: "Official Tournament Pack Vol. 5",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7927,
      name: "Online Regionals",
      release_date_jp: null,
      release_date_en: "2021-12-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 768,
      name: "PB-01: Tamer's Evolution Box",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 6475,
      name: "PB-02: Digimon Card Game Tamer's Set",
      release_date_jp: "2022-04-29",
      release_date_en: "2022-05-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 9346,
      name: "PB-03: WarGreymon Playmat",
      release_date_jp: "2022-06-29",
      release_date_en: "2022-09-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 6507,
      name: "PB-04: Digimon Card Game Tamer's Set 2",
      release_date_jp: "2021-09-01",
      release_date_en: "2021-12-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7806,
      name: "PB-05: Digimon Card Game Tamer's Set 3",
      release_date_jp: "2022-11-29",
      release_date_en: "2022-04-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 9084,
      name: "PB-06: Tamer's Evolution Box 2",
      release_date_jp: "2022-03-01",
      release_date_en: "2022-05-25",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 10129,
      name: "PB-07: Digimon Card Game Tamer's Set EX",
      release_date_jp: "2022-03-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 10132,
      name: "PB-08: Digimon Tamers Playmat",
      release_date_jp: "2022-03-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12042,
      name: "PB-09: Memorial Collection 01 Playmat",
      release_date_jp: "2022-06-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 12456,
      name: "PB-10: Digimon Card Game Tamer's Set 4",
      release_date_jp: "2022-06-29",
      release_date_en: "2022-09-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 3042,
      name: "Premium Bandai Apparel Promo Cards",
      release_date_jp: "2022-12-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 721,
      name: "Promo Sets",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 697,
      name: "Promotion Pack Ver 0.0",
      release_date_jp: "2020-02-29",
      release_date_en: "2021-01-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 1183,
      name: "Saikyo Jump Magazine Promo Cards",
      release_date_jp: "2021-10-04",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 1811,
      name: "Special Box Promotion Pack",
      release_date_jp: null,
      release_date_en: "2021-01-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 11758,
      name: "Special Promotion Pack 2022",
      release_date_jp: null,
      release_date_en: "2022-03-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13416,
      name: "Special Promotion Pack 2022 Ver.2.0",
      release_date_jp: null,
      release_date_en: "2022-05-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 3326,
      name: "Special Release Memorial Pack",
      release_date_jp: null,
      release_date_en: "2021-03-12",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13202,
      name: "Store Championship Participant Pack",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7928,
      name: "Store Championships",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 13121,
      name: "Ultimate Cup",
      release_date_jp: null,
      release_date_en: "2021-04-01",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 1181,
      name: "V-Jump Magazine Promo Cards",
      release_date_jp: "1970-01-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7706,
      name: "World Championship 2021",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 9352,
      name: "ST-10: Starter Deck Parallel World Tactician",
      release_date_jp: "2021-10-29",
      release_date_en: "2022-05-13",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 8757,
      name: "ST-11: Starter Deck Special Entry Deck",
      release_date_jp: "2021-11-26",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 11816,
      name: "ST-12: Starter Deck Jesmon",
      release_date_jp: "2022-04-22",
      release_date_en: "2022-10-14",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 11817,
      name: "ST-13: Starter Deck RagnaLoardmon",
      release_date_jp: "2022-04-22",
      release_date_en: "2022-10-14",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 649,
      name: "ST-1: Starter Deck Gaia Red",
      release_date_jp: "2020-04-24",
      release_date_en: "2021-01-29",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 683,
      name: "ST-2: Starter Deck Cocytus Blue",
      release_date_jp: "2020-04-24",
      release_date_en: "2021-01-29",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 682,
      name: "ST-3: Starter Deck Heaven's Yellow",
      release_date_jp: "2020-04-24",
      release_date_en: "2021-01-29",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 2474,
      name: "ST-4: Starter Deck Giga Green",
      release_date_jp: "2020-11-27",
      release_date_en: "2021-06-11",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 2475,
      name: "ST-5: Starter Deck Machine Black",
      release_date_jp: "2020-11-27",
      release_date_en: "2021-06-11",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 2476,
      name: "ST-6: Starter Deck Venomous Violet",
      release_date_jp: "2020-11-27",
      release_date_en: "2021-06-11",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 5573,
      name: "ST-7: Starter Deck Gallantmon",
      release_date_jp: "2021-04-23",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 5574,
      name: "ST-8: Starter Deck UlforceVeedramon",
      release_date_jp: "2021-04-23",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 7357,
      name: "ST-9: Starter Deck Ultimate Ancient Dragon",
      release_date_jp: "2021-10-29",
      release_date_en: "2022-05-13",
      series: "Digimon Card Game",
      type: "Starter Decks",
    },
    {
      id: 9999951,
      name: "Digimon Collectible Card Game Starter Set 1",
      release_date_jp: null,
      release_date_en: "2000-01-01",
      series: "Digimon Collectible Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999952,
      name: "Digimon Collectible Card Game Starter Set 2",
      release_date_jp: null,
      release_date_en: "2000-01-01",
      series: "Digimon Collectible Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999953,
      name: "Digimon The Movie Promo Cards",
      release_date_jp: null,
      release_date_en: "2000-10-06",
      series: "Digimon Digi-Battle Card Game",
      type: "Promo Sets",
    },
    {
      id: 9999954,
      name: "Series 1 Booster Pack",
      release_date_jp: null,
      release_date_en: "1999-06-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999955,
      name: "Series 1 Starter Set",
      release_date_jp: null,
      release_date_en: "1999-06-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999956,
      name: "Series 2 Booster Pack",
      release_date_jp: null,
      release_date_en: "2000-01-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999957,
      name: "Series 3 Booster Pack",
      release_date_jp: null,
      release_date_en: "2000-03-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999958,
      name: "Series 4 Booster Pack",
      release_date_jp: null,
      release_date_en: "2000-05-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999959,
      name: "Series 5 Booster Pack",
      release_date_jp: null,
      release_date_en: "2000-07-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999960,
      name: "Series 6 Booster Pack",
      release_date_jp: null,
      release_date_en: "2000-09-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999961,
      name: "Street Starter Set 1",
      release_date_jp: null,
      release_date_en: "2001-01-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999962,
      name: "Street Starter Set 2",
      release_date_jp: null,
      release_date_en: "2001-01-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999963,
      name: "Street Starter Set 3",
      release_date_jp: null,
      release_date_en: "2001-03-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 9999964,
      name: "Street Starter Set 4",
      release_date_jp: null,
      release_date_en: "2001-08-01",
      series: "Digimon Digi-Battle Card Game",
      type: "Booster Packs",
    },
    {
      id: 13702,
      name: "PB-11: Digimon Card Game Tamer's Set 5",
      release_date_jp: "2022-09-29",
      release_date_en: "2022-12-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 7158,
      name: "3 on 3",
      release_date_jp: "2021-08-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13267,
      name: "Bandai TCG Online Lobby Test Events",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 7153,
      name: "Battle of Omni Pre-Release Promotion",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13269,
      name: "December 2020 First Official Online Event",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 8791,
      name: "Double Diamond Pre-Release Promotion",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 6984,
      name: "Event Promo Cards",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 5961,
      name: "Great Legend Pre-Release Promotion",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13264,
      name: "March Premier TO Event",
      release_date_jp: null,
      release_date_en: "2021-03-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 6385,
      name: "Official Tournament Pack Vol. 2",
      release_date_jp: null,
      release_date_en: "2021-06-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 9256,
      name: "Official Tournament Pack Vol. 3",
      release_date_jp: null,
      release_date_en: "2021-10-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 11761,
      name: "Official Tournament Pack Vol. 4",
      release_date_jp: null,
      release_date_en: "2022-02-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 11028,
      name: "Special Promotion Pack 2021",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 3323,
      name: "Tamer Battle Pack 1",
      release_date_jp: "2022-08-29",
      release_date_en: "2022-03-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 11744,
      name: "Tamer Battle Pack 10",
      release_date_jp: "2022-03-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13099,
      name: "Tamer Battle Pack 11",
      release_date_jp: "2022-04-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 3324,
      name: "Tamer Battle Pack 2",
      release_date_jp: "2022-10-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 3325,
      name: "Tamer Battle Pack 3",
      release_date_jp: "2022-12-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 3912,
      name: "Tamer Battle Pack 4",
      release_date_jp: "2022-03-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 5703,
      name: "Tamer Battle Pack 5",
      release_date_jp: "2022-04-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 6726,
      name: "Tamer Battle Pack 6",
      release_date_jp: "2022-06-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 7704,
      name: "Tamer Battle Pack 7",
      release_date_jp: "2022-08-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 9216,
      name: "Tamer Battle Pack 8",
      release_date_jp: "2022-10-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 10318,
      name: "Tamer Battle Pack 9",
      release_date_jp: "2022-12-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 1184,
      name: "Tamer Exchange Event Promo Cards",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 6003,
      name: "Tamer Exchange Promotion Pack",
      release_date_jp: "2022-08-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 3041,
      name: "Tamer Party",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13303,
      name: "Tamer Party Vol.2",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13304,
      name: "Tamer Party Vol.3",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13305,
      name: "Tamer Party Vol.4",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 9257,
      name: "Winner Pack Double Diamond",
      release_date_jp: null,
      release_date_en: "2022-10-29",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13253,
      name: "Winner Pack New Awakening",
      release_date_jp: null,
      release_date_en: "1970-01-01",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 11766,
      name: "Winner Pack Next Adventure",
      release_date_jp: null,
      release_date_en: "2022-03-29",
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 7279,
      name: "Category:Events",
      release_date_jp: null,
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13801,
      name: "Level Up Matching Battle ONLINE August 2021",
      release_date_jp: "2021-08-29",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13810,
      name: "Level Up Matching Battle ONLINE February 2022",
      release_date_jp: "2022-02-26",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13804,
      name: "Level Up Matching Battle ONLINE May 2021",
      release_date_jp: "2021-05-30",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13807,
      name: "Level Up Matching Battle ONLINE November 2021",
      release_date_jp: "2021-11-28",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Events",
    },
    {
      id: 13916,
      name: "Draconic Roar EX-03",
      release_date_jp: "2022-07-29",
      release_date_en: "2022-11-11",
      series: "Digimon Card Game",
      type: "Booster Packs",
    },
    {
      id: 14162,
      name: "AB-01: Digimon Card Game Adventure Box",
      release_date_jp: null,
      release_date_en: "2022-07-29",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 14157,
      name: "Tamer Battle Pack 12",
      release_date_jp: "2022-06-01",
      release_date_en: null,
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 14181,
      name: "GB-02: Digimon Card Game Gift Box 2",
      release_date_jp: null,
      release_date_en: "2022-11-04",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
    {
      id: 14331,
      name: "PD-01: Premium Deck Set",
      release_date_jp: null,
      release_date_en: "2022-10-14",
      series: "Digimon Card Game",
      type: "Promo Sets",
    },
  ];

  return types;
}

export default digimonSets;
